#pragma once

#include "Sample.h"

/**
 * @file SampleBernoulli.h
 * @brief Contains the BernoulliSample class.
 */

 /**
  * @class BernoulliSample
  * @brief Sample generated by Bernoulli method.
  */
class BernoulliSample : public Sample
{
public:
    /**
     * @brief Creates a sample generated by the Bernoulli method.
     * @param dist Distribution used for simulation.
     * @param sample_size Number of observations in the sample.
     */
    BernoulliSample(const Distribution& dist, int sample_size);
    /**
     * @brief Simulates sample values using sequential Bernoulli trials.
     *
     * Simulated values are stored in the values field
     */
    void simulate() override;
};