#pragma once

#include "Sample.h"

/**
 * @file SampleInverse.h
 * @brief Contains the InverseSample class.
 */

 /**
  * @class InverseSample
  * @brief Sample generated by the inverse method.
  */
class InverseSample : public Sample
{
public:
    /**
     * @brief Creates a sample generated by the inverse method.
     * @param dist Distribution used for simulation.
     * @param sample_size Number of observations in the sample.
     */
    InverseSample(const Distribution& dist, int sample_size);
    /**
    * @brief Simulates sample values using the inverse method.
    * 
    * Simulated values are stored in the values field
    */
    void simulate() override;
};